// export {Home} from '@/screens/Home/Home';
// export {Login} from '@/screens/Login/Login';

// export {Profile} from '@/screens/Profile/Profile';
export {OnBoarding} from '@/screens/onBoarding';
export {Login} from '@/screens/login';
export {ForgotPassword} from '@/screens/forgotPassword';
export {RecoverViaEmail} from '@/screens/forgotPassword/component/RecoverViaEmail';
export {RecoverViaNumber} from '@/screens/forgotPassword/component/RecoverViaNumber';
export {VerifyByPhoneCode} from '@/screens/forgotPassword/component/VerifyByPhoneCode';
export {VerifyByEmailCode} from '@/screens/forgotPassword/component/VerifyByEmailCode';
export {CreateNewPassword} from '@/screens/forgotPassword/component/CreateNewPassword';
export {VerifyPhoneNumber} from '@/screens/verifyOtp';
export {VerifyOtp} from '@/screens/verifyOtp/component/VerifyOtp';
export {Home} from '@/screens/home';
export {ChooseVehicle} from '@/screens/chooseVehicle';
export {Booking} from '@/screens/booking';
export {Checkout} from '@/screens/checkout';
export {AddCardDetails} from '@/screens/checkout/component/AddCardDetails';
export {InvoiceDetail} from '@/screens/checkout/component/InvoiceDetail';
export {PersonalInfo} from '@/screens/menu/PersonalInfo';
export {EditInfo} from '@/screens/menu/EditInfo';
export {AddNewCard} from '@/screens/menu/AddNewCard';
export {TermConditions} from '@/screens/menu/TermConditions';
export {PrivacyPolicy} from '@/screens/menu/PrivacyPolicy';
export {ChangePassword} from '@/screens/menu/ChangePassword';
export {DeleteAccountBottomSheet} from '@/screens/menu/DeleteAccountBottomSheet';
export {PaymentMethod} from '@/screens/menu/PaymentMethod';
export {RideBookings} from '@/screens/menu/RideBookings';
export {Help} from '@/screens/menu/Help';
export {SupportChat} from '@/screens/menu/SupportChat';
