export const NAVIGATION = {
  onBoarding: 'OnBoarding',
  login: 'Login',
  forgotPassword: 'ForgotPassword',
  recoverViaEmail: 'RecoverViaEmail',
  recoverViaNumber: 'RecoverViaNumber',
  verifyByPhoneCode: 'VerifyByPhoneCode',
  verifyByEmailCode: 'VerifyByEmailCode',
  createNewPassword: 'CreateNewPassword',
  verifyPhoneNumber: 'VerifyPhoneNumber',
  verifyOtp: 'VerifyOtp',
  home: 'Home',
  chooseVehicle: 'ChooseVehicle',
  booking: 'Booking',
  checkout: 'Checkout',
  addCardDetails: 'AddCardDetails',
  invoiceDetail: 'InvoiceDetail',
  personalInfo: 'PersonalInfo',
  editInfo: 'EditInfo',
  addNewCard: 'AddNewCard',
  termConditions: 'TermConditions',
  privacyPolicy: 'PrivacyPolicy',
  changePassword: 'ChangePassword',
  deleteAccountBottomSheet: 'DeleteAccountBottomSheet',
  paymentMethod: 'PaymentMethod',
  rideBookings: 'RideBookings',
  help: 'Help',
  SupportChat : 'SupportChat',
};
